package main

// Word lists used by the synthetic data generator. Sized to give realistic
// 2-rune prefix distribution for the autotag match index — 500×500 first×last
// combinations is enough to populate 100k performers without heavy reuse of
// any single (first, last) pair.

var firstNames = []string{
	"James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda",
	"William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica",
	"Thomas", "Sarah", "Charles", "Karen", "Christopher", "Lisa", "Daniel", "Nancy",
	"Matthew", "Betty", "Anthony", "Sandra", "Donald", "Margaret", "Mark", "Ashley",
	"Paul", "Kimberly", "Steven", "Emily", "Andrew", "Donna", "Kenneth", "Michelle",
	"George", "Carol", "Joshua", "Amanda", "Kevin", "Melissa", "Brian", "Deborah",
	"Edward", "Stephanie", "Ronald", "Dorothy", "Timothy", "Rebecca", "Jason", "Sharon",
	"Jeffrey", "Laura", "Ryan", "Cynthia", "Jacob", "Amy", "Gary", "Kathleen",
	"Nicholas", "Angela", "Eric", "Shirley", "Jonathan", "Brenda", "Stephen", "Emma",
	"Larry", "Anna", "Justin", "Pamela", "Scott", "Nicole", "Brandon", "Samantha",
	"Benjamin", "Katherine", "Samuel", "Christine", "Gregory", "Helen", "Frank", "Debra",
	"Alexander", "Rachel", "Raymond", "Carolyn", "Patrick", "Janet", "Jack", "Maria",
	"Dennis", "Catherine", "Jerry", "Heather", "Tyler", "Diane", "Aaron", "Olivia",
	"Jose", "Julie", "Adam", "Joyce", "Henry", "Victoria", "Nathan", "Ruth",
	"Douglas", "Virginia", "Zachary", "Lauren", "Peter", "Kelly", "Kyle", "Christina",
	"Walter", "Joan", "Ethan", "Evelyn", "Jeremy", "Judith", "Harold", "Andrea",
	"Keith", "Hannah", "Christian", "Megan", "Roger", "Cheryl", "Noah", "Jacqueline",
	"Gerald", "Martha", "Carl", "Madison", "Terry", "Teresa", "Sean", "Gloria",
	"Austin", "Sara", "Arthur", "Janice", "Lawrence", "Ann", "Jesse", "Kathryn",
	"Dylan", "Abigail", "Bryan", "Sophia", "Joe", "Frances", "Jordan", "Jean",
	"Billy", "Alice", "Bruce", "Judy", "Albert", "Isabella", "Willie", "Julia",
	"Gabriel", "Grace", "Logan", "Amber", "Alan", "Denise", "Juan", "Danielle",
	"Wayne", "Marilyn", "Roy", "Beverly", "Ralph", "Charlotte", "Randy", "Natalie",
	"Eugene", "Theresa", "Vincent", "Diana", "Russell", "Brittany", "Louis", "Doris",
	"Bobby", "Kayla", "Philip", "Alexis", "Johnny", "Lori", "Bradley", "Marie",
	"Caleb", "Amelia", "Wesley", "Sophia", "Nathaniel", "Riley", "Chase", "Layla",
	"Colton", "Zoe", "Drew", "Nora", "Felix", "Lily", "Grant", "Aria",
	"Hudson", "Luna", "Hunter", "Stella", "Ian", "Hazel", "Isaac", "Aurora",
	"Jaxon", "Savannah", "Jude", "Brooklyn", "Julian", "Leah", "Levi", "Zoey",
	"Liam", "Penelope", "Lincoln", "Elena", "Lucas", "Violet", "Mason", "Paisley",
	"Maverick", "Isla", "Micah", "Claire", "Miles", "Scarlett", "Nolan", "Anna",
	"Oliver", "Ellie", "Owen", "Caroline", "Parker", "Audrey", "Preston", "Skylar",
	"Quentin", "Lucy", "Reed", "Genesis", "Reid", "Kennedy", "Rhys", "Madeline",
	"River", "Kinsley", "Roman", "Hailey", "Silas", "Nova", "Simon", "Willow",
	"Theodore", "Lydia", "Tobias", "Taylor", "Tristan", "Alaina", "Victor", "Peyton",
	"Wade", "Melanie", "Warren", "Serenity", "Weston", "Valentina", "Xander", "Allison",
	"Zane", "Addison", "Abel", "Kylie", "Abraham", "Autumn", "Adrian", "Lillian",
	"Ace", "Eva", "Adonis", "Lucia", "Alec", "Mila", "Alejandro", "Maya",
	"Alex", "Morgan", "Alonzo", "Naomi", "Amari", "Nevaeh", "Amir", "Paige",
	"Amos", "Piper", "Angel", "Ruby", "Anderson", "Sadie", "Andre", "Sienna",
	"Apollo", "Skyler", "Archer", "Summer", "Arian", "Sydney", "Ariel", "Trinity",
	"Arjun", "Valerie", "Armani", "Vanessa", "Asher", "Vera", "Ashton", "Vienna",
	"Atlas", "Violeta", "Atticus", "Wendy", "August", "Whitney", "Axel", "Winter",
	"Ayden", "Wren", "Baker", "Xena", "Barrett", "Yara", "Beau", "Yasmin",
	"Beckett", "Zaria", "Bennett", "Arabella", "Bentley", "Ariana", "Blake", "Athena",
	"Bodhi", "Blair", "Brady", "Camille", "Brantley", "Cora", "Braxton", "Daisy",
	"Brayden", "Delilah", "Brendan", "Eleanor", "Brennan", "Eliana", "Brett", "Esther",
	"Briggs", "Faith", "Brodie", "Freya", "Brooks", "Gianna", "Bryce", "Harper",
	"Byron", "Iris", "Cade", "Ivy", "Caden", "Jade", "Cael", "Josephine",
	"Caesar", "Juniper", "Cain", "Kira", "Calvin", "Lola", "Camden", "Mabel",
	"Cameron", "Mira", "Canaan", "Nadia", "Carson", "Nina", "Carter", "Noelle",
	"Casey", "Ophelia", "Cason", "Penny", "Cayden", "Phoebe", "Chandler", "Rosie",
	"Clay", "Sabrina", "Clayton", "Selena", "Clement", "Talia", "Cody", "Tessa",
	"Cohen", "Thea", "Cole", "Uma", "Colin", "Vada", "Collin", "Willa",
	"Conner", "Xenia", "Conor", "Yvette", "Cooper", "Zara", "Corbin", "Zoey",
	"Corey", "Aaliyah", "Cristian", "Ada", "Cruz", "Addilyn", "Dakota", "Adriana",
	"Dallas", "Aileen", "Damian", "Akira", "Damien", "Alana", "Damon", "Aliyah",
	"Dane", "Alma", "Daniel", "Althea", "Dante", "Alyssa", "Darian", "Amara",
	"Darius", "Anika", "Dash", "Annabelle", "Dawson", "Annalise", "Dean", "Ariana",
	"Declan", "Ariel", "Demetri", "Arya", "Derek", "Astrid", "Desmond", "Ayla",
	"Devon", "Azalea", "Dexter", "Bailey", "Diego", "Bella", "Dmitri", "Bellamy",
	"Dominic", "Belle", "Drake", "Bianca", "Easton", "Birdie", "Eddie", "Blair",
	"Edgar", "Blake", "Edison", "Blythe", "Edmund", "Bonnie", "Edwin", "Briar",
	"Eli", "Bridget", "Elias", "Brielle", "Elijah", "Brinley", "Elliot", "Bristol",
	"Elliott", "Brooke", "Emerson", "Brynlee", "Emmanuel", "Brynn", "Emmett", "Cadence",
}

var surnames = []string{
	"Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
	"Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas",
	"Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White",
	"Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker", "Young",
	"Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
	"Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell",
	"Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker",
	"Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales", "Murphy",
	"Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson", "Bailey",
	"Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson",
	"Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza",
	"Ruiz", "Hughes", "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers",
	"Long", "Ross", "Foster", "Jimenez", "Powell", "Jenkins", "Perry", "Russell",
	"Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes", "Gonzales", "Fisher",
	"Vasquez", "Simmons", "Romero", "Jordan", "Patterson", "Alexander", "Hamilton", "Graham",
	"Reynolds", "Griffin", "Wallace", "Moreno", "West", "Cole", "Hayes", "Bryant",
	"Herrera", "Gibson", "Ellis", "Tran", "Medina", "Aguilar", "Stevens", "Murray",
	"Ford", "Castro", "Marshall", "Owens", "Harrison", "Fernandez", "Mcdonald", "Woods",
	"Washington", "Kennedy", "Wells", "Vargas", "Henry", "Chen", "Freeman", "Webb",
	"Tucker", "Guzman", "Burns", "Crawford", "Olson", "Simpson", "Porter", "Hunter",
	"Gordon", "Mendez", "Silva", "Shaw", "Snyder", "Mason", "Dixon", "Munoz",
	"Hunt", "Hicks", "Holmes", "Palmer", "Wagner", "Black", "Robertson", "Boyd",
	"Rose", "Stone", "Salazar", "Fox", "Warren", "Mills", "Meyer", "Rice",
	"Schmidt", "Garza", "Daniels", "Ferguson", "Nichols", "Stephens", "Soto", "Weaver",
	"Ryan", "Gardner", "Payne", "Grant", "Dunn", "Kelley", "Spencer", "Hawkins",
	"Arnold", "Pierce", "Vazquez", "Hansen", "Peters", "Santos", "Hart", "Bradley",
	"Knight", "Elliott", "Cunningham", "Duncan", "Armstrong", "Hudson", "Carroll", "Lane",
	"Riley", "Andrews", "Alvarado", "Ray", "Delgado", "Berry", "Perkins", "Hoffman",
	"Johnston", "Matthews", "Pena", "Richards", "Contreras", "Willis", "Carpenter", "Lawrence",
	"Sandoval", "Guerrero", "George", "Chapman", "Rios", "Estrada", "Ortega", "Watkins",
	"Greene", "Nunez", "Wheeler", "Valdez", "Harper", "Burke", "Larson", "Santiago",
	"Maldonado", "Morrison", "Franklin", "Carlson", "Austin", "Dominguez", "Carr", "Lawson",
	"Jacobs", "Obrien", "Lynch", "Singh", "Vega", "Bishop", "Montgomery", "Oliver",
	"Jensen", "Harvey", "Williamson", "Gilbert", "Dean", "Sims", "Espinoza", "Howell",
	"Li", "Wong", "Reid", "Hanson", "Le", "Mccoy", "Garrett", "Burton",
	"Fuller", "Wang", "Weber", "Welch", "Rojas", "Lucas", "Marquez", "Fields",
	"Park", "Yang", "Little", "Banks", "Padilla", "Day", "Walsh", "Bowman",
	"Schultz", "Luna", "Fowler", "Mejia", "Davidson", "Acosta", "Brewer", "May",
	"Holland", "Juarez", "Newman", "Pearson", "Curtis", "Cortez", "Douglas", "Schneider",
	"Joseph", "Barrett", "Navarro", "Figueroa", "Keller", "Avila", "Wade", "Molina",
	"Stanley", "Hopkins", "Campos", "Barnett", "Bates", "Chambers", "Caldwell", "Beck",
	"Lambert", "Miranda", "Byrd", "Craig", "Ayala", "Lowe", "Frazier", "Powers",
	"Neal", "Leonard", "Gregory", "Carrillo", "Sutton", "Fleming", "Rhodes", "Shelton",
	"Schwartz", "Norris", "Jennings", "Watts", "Duran", "Walters", "Cohen", "Mcdaniel",
	"Moran", "Parks", "Steele", "Vaughn", "Becker", "Holt", "Deleon", "Barker",
	"Terry", "Hale", "Leon", "Hail", "Benson", "Haynes", "Horton", "Miles",
	"Lyons", "Pham", "Graves", "Bush", "Thornton", "Wolfe", "Warner", "Cabrera",
	"Mckinney", "Mann", "Zimmerman", "Dawson", "Lara", "Fletcher", "Page", "Mccarthy",
	"Love", "Robles", "Cervantes", "Solis", "Erickson", "Reeves", "Chang", "Klein",
	"Salinas", "Fuentes", "Baldwin", "Daniel", "Simon", "Velasquez", "Hardy", "Higgins",
	"Aguirre", "Lin", "Cummings", "Chandler", "Sharp", "Barber", "Bowen", "Ochoa",
	"Dennis", "Robbins", "Liu", "Ramsey", "Francis", "Griffith", "Paul", "Blair",
	"Oconnor", "Cardenas", "Pacheco", "Cross", "Calderon", "Quinn", "Moss", "Swanson",
	"Chan", "Rivas", "Khan", "Rodgers", "Serrano", "Fitzgerald", "Rosales", "Stevenson",
	"Christensen", "Manning", "Gill", "Curry", "Mclaughlin", "Harmon", "Mcgee", "Gross",
	"Doyle", "Garner", "Newton", "Burgess", "Reese", "Walton", "Blake", "Trujillo",
	"Adkins", "Brady", "Goodman", "Roman", "Webster", "Goodwin", "Fischer", "Huang",
	"Potter", "Delacruz", "Montoya", "Todd", "Wu", "Hines", "Mullins", "Castaneda",
	"Malone", "Cannon", "Tate", "Mack", "Sherman", "Hubbard", "Hodges", "Zhang",
	"Guerra", "Wolf", "Valencia", "Saunders", "Franco", "Rowe", "Gallagher", "Farmer",
	"Hammond", "Hampton", "Townsend", "Ingram", "Wise", "Gallegos", "Clarke", "Barton",
	"Schroeder", "Maxwell", "Waters", "Logan", "Camacho", "Strickland", "Norman", "Person",
	"Colon", "Parsons", "Frank", "Harrington", "Glover", "Osborne", "Buchanan", "Casey",
	"Floyd", "Patton", "Ibarra", "Ball", "Tyler", "Suarez", "Bowers", "Orozco",
}

var studioVocab = []string{
	"Acme", "Blackstone", "Crimson", "Dauntless", "Eastwood", "Fairweather", "Goldstream",
	"Harvest", "Ironcliff", "Jade", "Keystone", "Lumen", "Magnolia", "Northwind",
	"Obsidian", "Pinecrest", "Quicksilver", "Ravenwood", "Silverlake", "Timberline",
	"Umbra", "Vanguard", "Westshore", "Xenith", "Yellowstone", "Zenith",
	"Atlas", "Beacon", "Citadel", "Dynasty", "Emerald", "Forge", "Galaxy",
	"Helios", "Illumina", "Juniper", "Kestrel", "Lumina", "Meridian", "Nimbus",
	"Onyx", "Paragon", "Quartz", "Renegade", "Summit", "Titan", "Ultra",
	"Vertex", "Wildfire", "Xeon", "Yarrow", "Zephyr",
	"Apex", "Boreal", "Cascade", "Dawn", "Echo", "Flux", "Glacier",
	"Horizon", "Ivory", "Jet", "Kite", "Lush", "Mint", "Neon",
	"Orbit", "Prism", "Quantum", "Rift", "Storm", "Twilight", "Union",
	"Valor", "Wave", "Xero", "Yonder", "Zeroth",
	"Productions", "Studios", "Films", "Media", "Entertainment", "Pictures", "Works",
	"Group", "Labs", "Collective", "Lane", "Bros", "Corp", "Co", "Inc",
}

var tagVocab = []string{
	"outdoor", "indoor", "beach", "sunset", "forest", "mountain", "urban",
	"vintage", "modern", "casual", "formal", "amateur", "professional", "solo",
	"duo", "group", "portrait", "landscape", "night", "morning", "summer",
	"winter", "spring", "autumn", "travel", "studio", "natural", "dramatic",
	"cheerful", "moody", "black-and-white", "color", "wideangle", "closeup",
	"action", "quiet", "exotic", "classic", "experimental", "abstract",
	"sport", "leisure", "fashion", "artistic", "documentary", "candid",
	"editorial", "commercial", "fine-art", "fantasy", "minimalist", "bold",
	"soft", "harsh", "golden", "silver", "pastel", "vibrant", "muted",
	"monochrome", "warm", "cool", "neutral", "earthy", "metallic", "glossy",
	"matte", "rough", "smooth", "textured", "patterned", "geometric", "organic",
	"symmetric", "chaotic", "serene", "energetic", "romantic", "mysterious",
	"nostalgic", "futuristic", "rustic", "elegant", "playful", "sophisticated",
	"intimate", "epic", "grand", "humble", "lavish", "simple", "complex",
	"refined", "raw", "polished", "gritty", "crisp", "hazy", "dreamy",
	"crisp", "ethereal", "dynamic", "static", "fluid",
}
